/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Negocio.SopaBinaria;
import Util.*;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author madar
 */
public class GuiBinaria extends javax.swing.JFrame {

    /**
     * Creates new form GuiBinaria
     */
    public SopaBinaria sopa = new SopaBinaria();

    public GuiBinaria() {
        initComponents();
        ImageIcon fondo2 = new ImageIcon("src/Img/bann.png");
        Icon fondiu1 = new ImageIcon(fondo2.getImage().getScaledInstance(bann.getWidth(), bann.getHeight(), Image.SCALE_DEFAULT));
        bann.setIcon(fondiu1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        btnNumero = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        out = new javax.swing.JTextArea();
        pdf = new javax.swing.JButton();
        numero = new javax.swing.JTextField();
        bann = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 24)); // NOI18N
        jLabel1.setText("Sopa Binaria");

        btnCargar.setText("Cargar Excel Con la Sopa ");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnNumero.setText("Buscar un número decimal");
        btnNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroActionPerformed(evt);
            }
        });

        out.setColumns(20);
        out.setRows(5);
        out.setText("Se encontro del número decimal XXXX en binario : YYYY \nXXXX incidencias.");
        jScrollPane1.setViewportView(out);

        pdf.setText("Imprimir Resultado en PDF");
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfActionPerformed(evt);
            }
        });

        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(numero)
                                .addGap(29, 29, 29)
                                .addComponent(btnNumero)
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bann, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnCargar)
                        .addGap(67, 67, 67)
                        .addComponent(pdf)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bann, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(47, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumero)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargar)
                    .addComponent(pdf))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void btnNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroActionPerformed
        if (this.sopa.soupIsEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha cargado ningun documento Excel.");
        } else {
            int veces = sopa.getCuantasVeces_Diagonal(Integer.parseInt(this.numero.getText())) + sopa.getCuantasVeces_Vertical(Integer.parseInt(this.numero.getText())) + sopa.getCuantasVeces_Horizontal(Integer.parseInt(this.numero.getText()));
            this.out.setText("Se encontro del número decimal " + this.numero.getText() + " en binario : " + this.sopa.convertirBinario(Integer.parseInt(this.numero.getText())) + "\n" + veces + " incidencias.");
           
        }
    }//GEN-LAST:event_btnNumeroActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        JFileChooser archivo = new JFileChooser(".");
        archivo.showOpenDialog(this);
        //Colocando un filtro para archivos en excel (xls):
        FileFilter filtro = new FileNameExtensionFilter("Archivos excel", "xls");
        //Se le asigna al JFileChooser el filtro
        archivo.setFileFilter(filtro);
        File fileName = archivo.getSelectedFile();

        try {
            this.sopa.leerMatrizExcel(fileName.toString());
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnCargarActionPerformed

    private void pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfActionPerformed
           
        try {
            Document documento = new Document();
            FileOutputStream archivoPdf = new FileOutputStream("src/PDF_Generado/archivo.pdf");
            PdfWriter.getInstance(documento, archivoPdf);
            documento.open();
            PdfPTable table = new PdfPTable(this.sopa.soupData()[0].length);

            for (int i = 0; i < this.sopa.soupData().length; i++) {
                int count = 0;
                for (int j = 0; j < this.sopa.soupData()[0].length; j++) {
                    /*  PdfPCell cell = new PdfPCell(new Phrase("1"));
                     cell.setBackgroundColor(BaseColor.YELLOW);
                     table.addCell(cell);
                     */
                    if (this.sopa.soupData()[i][j].isValor()) {
                        PdfPCell cell = new PdfPCell(new Phrase("1"));
                        if (this.sopa.getPaintSopa()[i][j] == 1) {
                            cell.setBackgroundColor(BaseColor.YELLOW);

                        }
                        table.addCell(cell);

                    } else {
                        PdfPCell cell = new PdfPCell(new Phrase("0"));
                        if (this.sopa.getPaintSopa()[i][j] == 1) {
                            cell.setBackgroundColor(BaseColor.YELLOW);

                        }
                        table.addCell(cell);

                    }
                }

            }
            documento.add(table);
            documento.close();
        } catch (Exception e) {
        }
         this.sopa.setPaintSopaTotal();
    }//GEN-LAST:event_pdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiBinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiBinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiBinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiBinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiBinaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bann;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numero;
    private javax.swing.JTextArea out;
    private javax.swing.JButton pdf;
    // End of variables declaration//GEN-END:variables
}
